[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
  "-Clink-arg=--nmagic",
  "-Clink-arg=-Tlink.x",
  "-Clink-arg=-Tmemory.x",
  # Code-size optimizations.
  # This requires nightly atm.
  # "-Ztrap-unreachable=no",
  "-Cno-vectorize-loops",
  "-Cforce-frame-pointers=no",
]
runner = "./test.sh"

[build]
target = "thumbv8m.main-none-eabihf"
